[build]
  # instala deps en raiz y en frontend luego build:
  command   = "pnpm install && pnpm --filter frontend run build"
  publish   = "frontend/dist"            # si tu build de Vite sale a 'dist'
  functions = "netlify/functions"

[dev]
  command        = "pnpm --filter frontend dev"
  port           = 5173
  functionsPort  = 34567
